baseURL = "https://kullbach.net/"
languageCode = "en-us"
title = "kullbach.net"

[pagination]
  pagerSize = 5

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
